import { readFileSync, writeFileSync } from 'node:fs';
const path = 'assets-inline.js';
const src = readFileSync(path, 'utf8');
const start = src.indexOf('{');
const end = src.lastIndexOf('}') + 1;
if (start < 0 || end <= 0) throw new Error('no JSON object');
const obj = JSON.parse(src.slice(start, end));
const bg = readFileSync('assets/Castle Clashers Assets/Background.png');
obj.BACKGROUND = 'data:image/png;base64,' + bg.toString('base64');
const out = '// AUTO-GENERATED by embed-assets.mjs — do not edit by hand.\nwindow.ASSETS = '
  + JSON.stringify(obj, null, 2) + ';\n';
writeFileSync(path, out);
console.log('BACKGROUND injected,', (bg.length / 1024).toFixed(1), 'KB raw,',
  (out.length / 1024).toFixed(1), 'KB total');
